export const projects = [
    {
        id: 0,
        title: "Blood Bank Management System",
        date: "Aug 2023 - Oct 2023",
        description:
            "This comprehensive web application enhances blood donation processes, offering an intuitive interface for managing donor registrations, blood inventory, and appointment scheduling. Developed with PHP, Bootstrap, and MySQL, it ensures efficient matching of donors to recipients while providing robust reporting tools to support blood donation campaigns.",
        image: "/images/blood.png",
        tags: ["PHP", "MySQL", "Bootstrap"],
        category: "Web Application",
        github: "https://github.com/darshan45672/Blood-Bank-and-Donor-Management-system",
        webapp: "",
    },
    {
        id: 1,
        title: "Yoojak",
        date: "Aug 2023 - Oct 2023",
        description:
            "Yoojak is a modern placement management portal that automates the placement process, significantly reducing manual effort. Built using Laravel 11 and MySQL, it facilitates student registrations, job postings, and application tracking, providing a streamlined experience for students, recruiters, and administrators.",
        image: "/images/campus.png",
        tags: ["Laravel", "Livewire", "MySQL"],
        category: "Web Application",
        github: "https://github.com/darshan45672/Yoojak",
        webapp: "",
    },
    {
        id: 2,
        title: "Eventopia",
        date: "Aug 2023 - Oct 2023",
        description:
            "Eventopia revolutionizes institutional event management by automating scheduling, registration, and attendee tracking. Using the MERN stack with AWS and Docker, it offers high performance and real-time updates, ensuring a smooth experience for both administrators and participants.",
        image: "/images/event.png",
        tags: [
            "Next.js",
            "MongoDB",
            "GraphQL",
            "AWS",
            "Docker",
            "Redux",
            "JWT",
            "Prisma",
            "Reactstrap",
            "Nest.js",
        ],
        category: "Web Application",
        github: "https://github.com/darshan45672/Eventopia",
        webapp: "",
    },
    {
        id: 3,
        title: "Vyapaar Sampark",
        date: "Aug 2023 - Oct 2023",
        description:
            "Vyapaar Sampark is an eCommerce platform tailored for the agricultural sector, facilitating transactions and inventory management. Built with WordPress, it provides farmers and buyers an easy-to-use interface to connect, ensuring efficient sales and product visibility.",
        image: "/images/ecom.png",
        tags: ["WordPress", "Divi Builder", "eCommerce"],
        category: "WordPress",
        github: "",
        webapp: "https://vyaparsampark.com/",
    },
    {
        id: 4,
        title: "Buy Bee",
        date: "Aug 2023 - Oct 2023",
        description:
            "Buy Bee is a user-friendly eCommerce platform developed on WordPress, designed to sell a wide array of products. With features for secure transactions and seamless inventory management, it ensures high visibility for sellers and an enjoyable shopping experience for buyers.",
        image: "/images/ecom.png",
        tags: ["WordPress", "Elementor", "eCommerce"],
        category: "WordPress",
        github: "",
        webapp: "https://buyybee.com/",
    },
    {
        id: 5,
        title: "Shobha Digitals",
        date: "Aug 2023 - Oct 2023",
        description:
            "Shobha Digitals is a portfolio site designed to showcase photography elegantly. Built with WordPress and Divi Builder, it emphasizes load time optimization and SEO, providing a visually appealing platform for photographers to attract clients.",
        image: "/images/portfolio.png",
        tags: [
            "WordPress",
            "Divi Builder",
            "Photography",
            "Portfolio",
            "SEO",
        ],
        category: "WordPress",
        github: "https://github.com/Ahmadmidlaj/VideoStreamingApp",
        webapp: "https://lovely-sprinkles-7289fd.netlify.app/",
    },
    {
        id: 6,
        title: "Portfolio",
        date: "Aug 2023 - Oct 2023",
        description:
            "A personal portfolio project to manage college events effectively. Developed with React.js and REST API, it showcases projects and enhances event management efficiency.",
        image: "/images/portfolio.png",
        tags: ["React.js", "REST API"],
        category: "Static",
        github: "",
        webapp: "https://lovely-sprinkles-7289fd.netlify.app/",
    },
    {
        id: 7,
        title: "My Personal Blog Site",
        date: "June 2024",
        description:
            "This blog site serves as a platform to share personal insights and experiences. Built with Astro.js and Tailwind CSS, it offers a clean and responsive design for easy navigation.",
        image: "/images/blog.png",
        tags: ["Astro.js", "Tailwind CSS"],
        category: "Static",
        github: "",
        webapp: "https://lovely-sprinkles-7289fd.netlify.app/",
    },
];
