export const experiences = [
    {
        id: 0,
        img: "https://github.com/darshan45672/c-progrms/assets/109609462/d4ae5f62-234e-4db7-bf99-c4738664d87a",
        role: "Application Developer Intern",
        company: "Headway, Mangalore",
        date: "May 2024 - Present",
        desc: "At Headway, I developed a state-of-the-art job hiring application using TypeScript, Next.js, Neon.js, PostgreSQL, and Prisma. This project enhanced user experience and streamlined job postings, showcasing my ability to leverage modern tech stacks for effective solutions.",
        skills: [
            "TypeScript",
            "Next.js",
            "Neon.js",
            "PostgreSQL",
            "Prisma",
            "User Experience Design",
        ],
    },
    {
        id: 1,
        img: "https://github.com/darshan45672/bank/assets/109609462/7db80061-81a0-4293-9d0f-2acbdcf4de69",
        role: "Virtual Lab Developer Volunteer",
        company: "Center for System Design, NITK",
        date: "January 2024 - May 2024",
        desc: "I volunteered at the Center for System Design NITK, contributing to the development of virtual labs and virtual reality projects. My role involved hands-on work in designing and implementing virtual labs in web and work on virtual reality projects, harnessing technology to enhance learning experiences.",
        skills: ["HTML5", "CSS3", "Javascript", "P5.JS", "Unity", "UnReal"],
    },
    {
        id: 2,
        img: "https://github.com/darshan45672/bank/assets/109609462/7db80061-81a0-4293-9d0f-2acbdcf4de69",
        role: "Virtual Lab Developer Intern",
        company: "Center for System Design, NITK",
        date: "October 2023 - November 2023",
        desc: "As an intern at the Center for System Design NITK, I focused on developing virtual labs and simulations. During my internship, I gained valuable experience in designing and implementing virtual environments aimed at enhancing learning through simulation-based activities.",
        skills: ["HTML5", "CSS3", "JavaScript", "jQuery", "ChartJS", "Plotly"],
    },
    {
        id: 3,
        img: "https://github.com/darshan45672/c-progrms/assets/109609462/3b72deb4-2f3a-474c-8943-1ec87f72c4b8",
        role: "Web Designer",
        company: "Klientship",
        date: "June 2023 - Present",
        desc: "As a freelancer at Klientship Private Limited, I specialized in web design using no-code tools, particularly WordPress. I leveraged these tools to create visually appealing and functional websites for clients, delivering tailored solutions to meet their needs efficiently.",
        skills: [
            "Wordpress",
            "Elementor",
            "Woo Commerce",
            "SEO",
            "Client Interactivity",
        ],
    },
    {
        id: 4,
        img: "https://github.com/darshan45672/Portfolio/assets/109609462/e859b403-8c2f-46c2-8de0-768ffd7bc86d",
        role: "Web Designer",
        company: "Market Bird ",
        date: "May 2023 - June 2023",
        desc: "As an intern at Market Bird India, I specialized in web design using WordPress, mastering Divi Builder and Elementor. Additionally, I gained expertise in Search Engine Optimization (SEO) and gained insights into Digital Marketing practices. Throughout the internship, I successfully managed projects for international clients, ensuring their satisfaction by fulfilling all their requirements.",
        skills: [
            "Wordpress",
            "Divi Builder",
            "Elementor",
            "Search Engine Optimization (SEO)",
            "Digital Marketing",
            "Event Promotion",
            "Client Interactivity",
        ],
    },
    {
        id: 5,
        img: "https://media.licdn.com/dms/image/D560BAQFV0JYJ33yONg/company-logo_200_200/0/1691701552297/bharat_intern_logo?e=2147483647&v=beta&t=-sDv95pGdL1U0O5_PI5teiuiB8D1SVcyswsXm3CE7RU",
        role: "Basic Web Development ",
        company: "Bharat Intern",
        date: "March 2023 - April 2024",
        desc: "I interned at Bharat Intern, where I focused on basic web development using HTML, CSS, and JavaScript. During this internship, I acquired foundational skills in building simple web projects, gaining hands-on experience that laid the groundwork for my understanding of web development principles.",
        skills: ["HTML", "CSS", "JavaScript", "Boostrap"],
    },
];